version: '3'
services:
  flask:
    build: backend
    command: flask run -h 0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=5001
      - FLASK_RUN_HOST="0.0.0.0"
    ports: 
      - '5001:5001'
    depends_on:
      - prometheus


  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    ports:
      - '9091:9091'
    volumes:
      - ./prometheus/pushgateway.yml:/etc/pushgateway.yml
    command:
      - '--web.enable-lifecycle'

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CREATE_TOPICS=latitude:1:1,longitude:1:1,altitude:1:1,battery:1:1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
      - prometheus

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes

  jmx-exporter:
    image: sscaling/jmx-prometheus-exporter:0.12.0
    ports:
      - '5556:5556'
    volumes:
      - ./prometheus/jmx-exporter.yml:/config.yml
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  scooter-simulator:
    build: scooter-simulator
    command: python producer.py
    depends_on:
      - kafka
      - prometheus